<a href="https://colab.research.google.com/github/ellenribeirolucena/PDS-FFT/blob/main/Implementa%C3%A7%C3%A3o_FFT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Teste 1: entrada 11111111 | saída esperada: 00000000

Teste 2: entrada 10000000 | saída esperada: 11111111

In [ ]:
import numpy as np
#PRÉ-DEFINIÇÕES:
N = 8                                   # Tamanho da FFT
x = [1, 1, 1, 1, 1, 1, 1, 1]#[1,0,0,0,0,0,0,0]#[0,1,0,0,0,0,0,0]                   # Entrada da FFT 
etapas = np.arange(1,int(np.log2(N))+1) # Etapas necessárias para FFT
XM=np.zeros((len(etapas)+1,N))          # Vetor que percorre as etapas da FFT
#print(XM)

In [ ]:
# Função que calcula o bit reverso:
def revbits(x):
    return int(bin(x)[2:].zfill(len(etapas))[::-1], 2)

# Definição da sequência do vetor de entradas para FFT:
for k in range(N):
  XM[0,k] = x[revbits(k)]
  #print(revbits(k))
print(XM)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#print('\n TMP_Entrada = \n',XM)
for m in etapas:
  Nk = 2**m                                   # Nk = Tamanho da FFT na etapa m
  print('Etapa nº',m,'(',int(N/Nk),'FFTs de N =',Nk,')')
  for k in range(int(N/Nk)):                  # N/Nk = Número de FFTs de tamanho Nk realizadas
    print(' FFT',k,'da etapa',m,'( N =',Nk,')')
    rep = 2**(m-1)                            # rep = Repetições de p para cada FFT
    p = k*Nk
    for kp in range(rep):
      print('   Repetição', kp,'( p =',p,') da FFT',k,'( N =',Nk,')')
      q = p+2**(m-1)
      m_1 = m-1
      print('p = ', p)
      print('q = ', q)
      r = (N/2)**m     #segundo p.438 do
      print('r = ',r)                         
      W = np.cos(2*np.pi*r/N) - 1j*np.sin(2*np.pi*r/N)
      XM[m,p] = XM[m_1,p]+W*XM[m_1,q]
      XM[m,q] = XM[m_1,p]-W*XM[m_1,q]
      p = p + 1
      print('\n TMP = \n',XM)
print('\n RESPOSTA = \n',XM)

Etapa nº 1 ( 4 FFTs de N = 2 )
 FFT 0 da etapa 1 ( N = 2 )
   Repetição 0 ( p = 0 ) da FFT 0 ( N = 2 )
p =  0
q =  1
r =  4.0

 TMP = 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
 FFT 1 da etapa 1 ( N = 2 )
   Repetição 0 ( p = 2 ) da FFT 1 ( N = 2 )
p =  2
q =  3
r =  4.0

 TMP = 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 2. 0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
 FFT 2 da etapa 1 ( N = 2 )
   Repetição 0 ( p = 4 ) da FFT 2 ( N = 2 )
p =  4
q =  5
r =  4.0

 TMP = 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 2. 0. 2. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
 FFT 3 da etapa 1 ( N = 2 )
   Repetição 0 ( p = 6 ) da FFT 3 ( N = 2 )
p =  6
q =  7
r =  4.0

 TMP = 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 2. 0. 2. 0. 2. 0. 2.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Etapa nº 2 ( 2 FFTs de N = 4 )
 FFT 0 da etapa 2 ( N = 4 )
   Repetição 0 ( p = 0 ) da FFT 0 ( N = 4 )
p =  0
q =

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:18: ComplexWarning: Casting complex values to real discards the imaginary part
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: ComplexWarning: Casting complex values to real discards the imaginary part
